[package]
name = "stonksfich"
version = "0.1.0"
authors = ["Claus Martinsen <clauswrm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
chess = "3.1.1"
colored = "2.0.0"
