[package]
name = "chess"
version = "0.1.0"
authors = ["Claus Martinsen <clauswrm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = { git = "https://github.com/jordanbray/chess.git" }
